spring:
  flyway:
    enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/kata?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:kata}
    password: ${SPRING_DATASOURCE_PASSWORD:kata}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
